# Generated by Django 4.2.7 on 2023-12-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_average', models.FloatField(default=0.0)),
                ('g_average', models.FloatField(default=0.0)),
                ('b_average', models.FloatField(default=0.0)),
            ],
        ),
    ]
