# Generated by Django 4.2.7 on 2023-12-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_hsv', models.CharField(default='', max_length=255)),
                ('average_lab', models.CharField(default='', max_length=255)),
                ('average_rgb', models.CharField(default='', max_length=255)),
                ('l_value', models.FloatField(default=0.0)),
                ('b_value', models.FloatField(default=0.0)),
                ('s_value', models.FloatField(default=0.0)),
            ],
        ),
    ]
