# Generated by Django 4.2.8 on 2023-12-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0003_rename_g_average_analysis_l_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='personal_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_color',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
