# Generated by Django 4.2.8 on 2024-01-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0006_analysis_best_draping_1_analysis_best_draping_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_1',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_2',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_3',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_4',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_5',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_6',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_7',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='best_draping_8',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_1',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_2',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_3',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_4',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_5',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_6',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_7',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='second_draping_8',
        ),
    ]
