# Generated by Django 4.2.9 on 2024-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0009_rename_is_wearing_wearingdetect_cap_wearing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='b',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='s',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='v',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
