# Generated by Django 4.2.9 on 2024-04-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0009_rename_is_wearing_wearingdetect_cap_wearing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WearingDetect',
        ),
    ]
