# Generated by Django 4.2.8 on 2023-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycol_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
