# Generated by Django 4.2.8 on 2023-12-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0004_analysis_personal_color_analysis_second_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='b_average',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='l_average',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='s_average',
        ),
    ]
