# Generated by Django 4.2.8 on 2024-01-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0005_remove_analysis_b_average_remove_analysis_l_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='best_draping_1',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_2',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_3',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_4',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_5',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_6',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_7',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='best_draping_8',
            field=models.ImageField(blank=True, null=True, upload_to='best_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_1',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_2',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_3',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_4',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_5',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_6',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_7',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='second_draping_8',
            field=models.ImageField(blank=True, null=True, upload_to='second_draping/'),
        ),
    ]
