# Generated by Django 4.2.9 on 2024-01-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0007_remove_analysis_best_draping_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearingDetect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wearing', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
