# Generated by Django 4.2.9 on 2024-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycol_app', '0010_delete_wearingdetect'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='b',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='face_analysis_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='s',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='v',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
